version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/todolist-api/Dockerfile
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./apps/todolist-api:/app
      - /app/node_modules
    command: yarn run dev

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/todolist-frontend/Dockerfile
    restart: always
    volumes:
      - ./apps/todolist-frontend:/app
      - /app/node_modules
    depends_on:
      - api
    command: yarn run dev

  proxy:
    image: nginx:1.19.4
    depends_on:
      - api
      - frontend
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

